# -*- coding: utf-8 -*-
"""Day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BqJ1XvQzPze9m5-A9qMbQINXIl66jOtc
"""

a=input("Enter the Password:")
while a== "1234":
    print("Wrong Password")
    a=input("Enter the Password again:")
print("Welcome to Shimakh")

i=1
while i<=10:
    print("welcome to shimakh", i)
    i+=1#i=i+1

n=int(input("enter the num: "))
sum=0
while n>0:
    sum+=n#
    n-=1
    print("these are n values:", n)
    print("these are sum of values:", sum)

break, continue, pass

#break point
sum1=0
while True:
    num =int(input("enter the number: "))
    sum1+=1
    print(sum1)
    if num==0:
        break
    print("come out from loop", sum)

num=1
while num<=10:
    num+=1
    if num==5:
        continue
    print(num)

a="ganesh"
for i in a:
    if i=="n":
        continue
    print(i, end=" ")

num=0
while len(a)>num:
    a=input("enter name:")
    if a=="radha":
        continue
    num+=1
    print(a)

num=0
while len(a)>num:
    a=input("enter name:")
    if a=="radha":
        pass
    num+=1
    print(a)

num=0
while len(a)>num:
    a="ganesh"
    if a=="ganesh":
        continue
    num+=1
    print(a)

a="ganesh"
for i in a:
    if i=="n":
        pass
    print(i, end=" ")

def add():
    pass

class Add:
    pass