# -*- coding: utf-8 -*-
"""Day4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WwORBATdEuEbL-k9Lpc7BtbeDL_WNbqw
"""

#split
date1="11-10-2023"

date1[6:]

a=date1.split("-")

type(a)

len(a)

a[0]

type(a[1])

a

for i in a:
    print(int(i), end="-")

ip ="192.168.10.11/25"

ip.split("/")

ip.split(".")

ip.split(".")[-1]

ip.split(".",1)

?ip.rsplit

ip.rsplit(".",1)

ip.rsplit(".") #same as ip.split(".")

#Justify method
1. ljust()
2. rjust()
3.center()
4.zfill()

str1="ganesh"

len(str1)

str1.ljust(10,"@")

str1.rjust(10,"@")

str1.center(20,"@")

str1.zfill(10)

l1=["ganesh","rajesh","hareesh"]
age=30
marks=90

"""#Expected output
#name    age marks
#ganesh  30  90
#rajesh 30 90
#hareesh 30 90
"""

for i in l1:
    print(i,"--->", age, marks)

len("ganesh")

for i in l1:
    print(i.ljust(7),"--->",age,marks)

bin(16)

bin(16)[2:]

'00000000010000'

bin(16)[2:].zfill(16)

#replace
#join

str2="######ganesh"

?str2.replace

str2.replace("#"," ",-1)

help(str2.join)

"#".join(str2)

date1

l2=date1.split("-")

("/").join(l2)

"11/10/2023"

date1.replace("-","/")

l3=["a.pdf","b.pdf","c.txt","a.txt"]
for i in l3:
    print(i)

l3=["a.pdf","b.pdf","c.txt","a.txt"]
for i in l3:
    if i.startswith("a"):#deep learning or machine learning
        print(i)

l3=["a.pdf","b.pdf","c.txt","a.txt"]
for i in l3:
    if i.endswith("pdf"):#deep learning or machine learning
        print(i)

"hello".startswith("H")

"123".isdigit()

" 123".isdigit()

"w123".isdigit()

a=input("enter the value: ")
if a.isdigit():
    a=eval(a)#evaluate expression
    print(a, type(a))

"a123".isdigit()

#isalpha

"is".isalpha()

"is7".isalpha()

#isalnum=alpha+numerical

"intel".isalnum()

"intel7".isalnum()

"intel7#".isalnum()

#String methods

len()
min()
max()

str1="python program"

min(str1)#depands on ASCII value

min(1,2,4)

max(1,2,4)

str1.split(" ")

max(str1)

ord("y")

ord("Y")

ord(" ")

for i in str1:
    print(i,"--->",ord(i))

max("hello#")

ord("#")

for i in "hello#":
    print(i,"--->",ord(i))

min("hello#")

"is".islower()

"iT".isupper()

"iT".islower()

"python program".isspace()

" ".isspace()

"@a".isidentifier()

@a=3

"_a".isidentifier()

"1w".isdecimal()

"1.2".isdigit()

"11.2".isnumeric()

w="ganeshn\nradha"

w.splitlines()

a="ganesh"
b ="this is "
print("hi everyone {} {}".format(a, b))

#list data type
list is collection of sequaence data type
it is heterogeneus data type
List is mutable data types
it is non-primitive data type

list1=[1,2,3]

type(list1)

l2=[]

type(l2)

#append is adding element end of list only one element

l2.append(1)

l2

l2.append("3")

l2

#extend we can mulitple values
l2.extend([1,2,3])

l2.clear()

l2

l2.insert(2,"e")

l2.index("e")

l2.count(1)

l2.pop()

l2

l2.remove(1)

l2

l2.remove("e")

l2

l3=l2.copy()

l3

id(l3) #because mutable datatype

id(l2)

l4=[1,2,3]

l5=[1,3,2]

l4==l5

l5.sort(reverse=True)

l5

r=["q","s","t"]

r.reverse()

r.

#indexing and slicing

#tuple is
list is collection of sequaence data types
it is heterogeneus data type
List is immutable data types can't change
it is non-primitive data type
tuple is starts ()
empty tuple is ()

tpl=()

print(type(tpl))

tp2=(1)

type(tp2)

tp3=(1,)

type(tp3)

tp3=(1,2,3,"w","r")

tp3

tup4= 1,2,3,"w","r"

tup4

tup4[1]

A=("ganesh","radha","hareesh")
A[2]#A[-1]

#arrays are -------->homogeneueos
#tuple and list are heterogeneuoes

l6=[1,2,3,"ty"]

import array

array.array('i',(1,2,"d",4))

array.array('f',(1.2,2,3,3))

import numpy as np

np.arange(20) #arange is numpy function

l1=[1,2,3]
l2=[1,2,3]

l1+l2 #concatenation not addition

a1=array.array('i',(1,2,3))

a2=array.array('i',(1,2,3))

a1+a2

n1=np.arange(3)

n2=np.arange(3)

n1

n2

n1+n2 #addition

l1*l2

l1-l2 +,*,**,/,%,//,-

1/2 #simple division

5%2 #remainder division

5//2 #floor division

import math

dir(math)

math.factorial(5)

math.floor(2.6)

math.ceil(2.6)

import os

os.getcwd()

os.mkdir("ganesh")

os.cd("ganesh")

A

type(A[0])

#slicing
A[0:2]

A[:]

A[::-1]

A[0][0]

l8=['ganesh', 'radha', 'hareesh']

l8[0][0]

#unpacking

tp4=(1,2)

print(tp4)

a,b=tp4

a

b

a,b,c=(10,20)

a,b,*c=(10,20,30,30)

c

tp5=tp4

tp4

tp5

id(tp4)

id(tp5)

#because it is immuatable

#Update list
A=[1,2,4]

A[1]=3

A

#update tuple

A=(1,2,4)

# Convert the tuple to a list
tuples = (0, 2, 4, 6, 8)
mylist = list(tuples)

mylist[4]=21

mylist

t=tuple(mylist)
print(t)

A

A[1]=3

t1=(1,2,3,3,4,5,6,6,7,7)

t1.count(3)

t1.index(7)

#to get the all the occurances right from the loop

t2=(10,20,10)

t1+t2

#no mutlipication tuple with tuple
t1*2#t1+t1

print(t2[0])

print(t2[2])

id(t2[0])

id(t2[2])

